name: Upload tool cache

on: workflow_dispatch

jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
